---
title: "SimplyQCNP hydrological and carbon, nitrate and phosphorus model"
format: html
editor: source
---

```{r, echo = FALSE, warning = FALSE}
library(reticulate)
use_condaenv("mobius", required = TRUE)
```


# Introduction
This is based on the SimplyQ Quarto document, but modified to try to get it working for carbon, NO3 and phosphorus. There are recording stations from LOIS at Boleside = Reach 12 = UpperTweed, and at Norham = Reach 23 = LowerTweed. Just used default values from example on Mobius website to get it started. Note that water quality data is much less frequent than temperature, rainfall and Q, but in theory it should still work.

R script CNP needed. There also seems to be a separate sediment component to the model.


```{python import_libs}
#| echo: false
import sys
import subprocess
print(sys.executable)
import matplotlib.pyplot as plt
import warnings
import pickle
import lmfit
import os
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import datetime as dt
from importlib.machinery import SourceFileLoader
import networkx
import numdifftools
import runpy
import time

# Styling
warnings.filterwarnings("ignore")
plt.style.use('ggplot')
```
# 1 Introduction
This is based on the simplyP example Jupyter notebook which seems the best
documented of the set.

```{python}
#| echo: false
# Initialise wrapper
wr = SourceFileLoader("mobius", r"python/mobius.py").load_module()
cu = SourceFileLoader("mobius_calib_uncert_lmfit", r"python/mobius_calib_uncert_lmfit.py").load_module()

wr.initialize('lib/simplyn.so')   # .so on Linux
```

# 2. Load observed datasets and model structure
This should happen next

```{python apply_filenames}
#| echo: false
#current_dir = os.getcwd()
#two_dirs_up = os.path.abspath(os.path.join(current_dir, "tweed_unified"))
params_path = os.path.join("data", "simplyQN_parameters.dat")
inputs_path = os.path.join("data", "simplyQN_datainputs.dat")
# Use the dynamically constructed paths
dataset = wr.DataSet.setup_from_parameter_and_input_files(params_path, inputs_path)

```


# 3. Link simulated and observed datasets
Also does comparisons which is where need to check.

```{python}
#| echo: false
comparisons = [
    ('Reach flow (daily mean, cumecs)', ['UpperTweed'], 'observed Q', ['UpperTweed']),
    ('Reach flow (daily mean, cumecs)', ['LowerTweed'], 'observed Q', ['LowerTweed']),
    ('Reach DIN concentration (volume weighted daily mean)', ['UpperTweed'], 'observed NO3', ['UpperTweed']),
    ('Reach DIN concentration (volume weighted daily mean)', ['LowerTweed'], 'observed NO3', ['LowerTweed']),
]
```


# 4. Manual calibration
This should print out a reasonable-looking table but has caused problems. Coded
reaches as r1 and r2 to match a comment in one file by Leah Jackson-Blake.

```{python}
#| echo: false
#index_short_name = {'All':'A', 'Quick':'q', 'Soilwater':'s', 'Groundwater':'g', 'UpperTweed':'r', 'LowerTweed':'r'}
index_short_name = {'Arable':'A', 'Improved grassland':'IG', 'Semi-natural':'SN', 'UpperTweed':'r1', 'LowerTweed':'r2'}

param_df = cu.get_double_parameters_as_dataframe(dataset, index_short_name=index_short_name)

pd.options.display.max_rows = 999

param_df
```

Note the index column in this dataframe, which specifies how each parameter varies within the model structure. For example, the Vegetation cover factor takes different values for different land use classes, while the Mean slope of land parameters vary both by land class and river reach.

For this particular dataset, the default values in the initial_value column were from LJ-B example informed by manual calibration. We can easily run the model with these values and assess the goodness-of-fit. The functions below produce one plot and one set of summary statistics for each dataset in comparisons.


```{python}
#| echo: false
#| scrolled: true
dataset.run_model()
# Print goodness of fit
cu.print_goodness_of_fit(dataset, comparisons)

# Plot objective
cu.plot_objective(dataset, comparisons)
plt.show()
```

# 5. Auto-calibration
## 5.1 Choose parameters to calibrate
This should be informed by system knowledge.

```{python}
#| echo: false
wanted_names = [
    'DDFmelt', 'DDET', 'Ts', 'fc', 'ETP', 'fquick', 'bfi',
    'Q10den', 'den', 'DINgw', 'DINin', 'DINeff', 'sensors',
]
# The following code selects any parameter with short_name *beginning* with any
# of the strings in the 'wanted_names' list. This means e.g. that if you replace
# 'Ts_SN' with 'Ts' in the above list, it will select all the parameters
# starting with Ts, i.e. all the soil water time constants.
calib_df = param_df[[any([sn.startswith(n) for n in wanted_names]) for sn in param_df['short_name']]].reset_index(drop=True)
calib_df
```

Having defined a dataframe of parameters we wish to calibrate, complete with short names, initial values and minimum to maximum ranges, we can instantiate an LMFit Parameters object, which makes it easy to keep track of bounded parameter values. Here, suffixes _A, _IG and _SN refer to arable, improved grassland and semi-natural. r1 and r2 would be reach 1 (UpperTweed), and reach 2 (LowerTweed) etc., but need to be in list originally.

```{python}
#| echo: false
# Convert to LMFit parameter object
params = cu.parameter_df_to_lmfit(calib_df)


# Set param_df based on separate calibration of just simplyQ
params['DDET_A'].value = 0.0532
params['DDET_IG'].value = 0.199
params['DDET_SN'].value = 0.141
params['DDFmelt'].value = 1.52
params['ETPtmin_A'].value = -2.16
params['ETPtmin_IG'].value = -4.45
params['ETPtmin_SN'].value = -4.59
params['Ts_A'].value = 3.28
params['Ts_IG'].value = 1.27
params['Ts_SN'].value = 40
params['bfi'].value = 0.0139
params['fc_A'].value = 635
params['fc_IG'].value = 185
params['fc_SN'].value = 258
params['fquick'].value = 2.28e-06
params['DDET_A'].vary = False
params['DDET_IG'].vary = False
params['DDET_SN'].vary = False
params['DDFmelt'].vary = False
params['ETPtmin_A'].vary = False
params['ETPtmin_IG'].vary = False
params['ETPtmin_SN'].vary = False
params['Ts_A'].vary = False
params['Ts_IG'].vary = False
params['Ts_SN'].vary = False
params['bfi'].vary = False
params['fc_A'].vary = False
params['fc_IG'].vary = False
params['fc_SN'].vary = False
params['fquick'].vary = False

```

It is possible to modify prior ranges for each paramter. Initial values can also be changed using e.g. params['DDFmelt'].value = 2.5, and calibration can be disabled entirely for specific parameters using e.g. params['DDFmelt'].vary = False. Note that parameters must be referred to by their short_name attribute. Note: params will return a dataframe showing the current user choices for the calibrating parameters. (In a Python script/terminal, params.pretty_print provides similar output).

```{python}
#params['DDFmelt'].min = 0.5
#params['DDFmelt'].max = 5.0

params.pretty_print(precision = 3)
```

## 5.2 Least-squares optimisation
LMFit provides a convenient API to several Python optimisers (see here for details).

Some of these optimisers also provide confidence intervals and correlations for the "best" parameters. These are approximate, but they provide useful information about the model and may help you to refine parameter ranges (or even the model structure) before undertaking a more comprehensive calibration exercise using MCMC (see below).

All of these optimisers aim to minimise the sum of squared residuals. From a "formal" statistical point of view, this is equivalent to assuming a likelihood function with independent and identically distributed (i.i.d.) Gaussian errors, which may not be the best choice. Nevertheless, minimising the sum of squared errors is often a good starting point, especially given the range of optimisers available.

Note: Performance can vary dramatically between optimisers, so it's often a good idea to try a few different alternatives. This will also allow you to check whether the same "optimum" is identified by the various algorithms.


```{python}
#| echo: false
#| scrolled: true
# Minimise using Levenberg–Marquardt (gives similar output to Nelder-Mead, 
# but in this case it's faster)
start_time = time.time()
mi, res = cu.minimize_residuals(params, dataset, comparisons, method='nelder', norm=False, skip_timesteps=365)
print('Optimization results\n')
lmfit.report_fit(res)
print('\n\nOptimized parameter values:\n')
res.params.pretty_print(precision=3)
end_time = time.time()
execution_time = end_time - start_time
print(f"Execution time: {execution_time} seconds")

cu.set_parameter_values(res.params, dataset)
if not os.path.exists('results'):
    os.makedirs('results')
dataset.write_parameters_to_file('results/optimized_params.dat')
```

The optimiser has run the model roughly 500 times in around 50 seconds. Output includes estimated parameter correlations and confidence intervals: note, for example, the Stderr column that has been added to the parameters table immediately above. If there are any correlations between the parameters above 0.1 these will also be displayed.


## 5.3 Visualise results
To see the model output for the optimised parameter values, first use set_parameter_values to update the default values, and then re-run the model, as above.

```{python}
cu.set_parameter_values(res.params, dataset)
dataset.run_model()
cu.print_goodness_of_fit(dataset, comparisons)
cu.plot_objective(dataset, comparisons)
plt.show()
```

Comparing the goodness-of-fit statistics from the optimiser to those from the manual calibration (section 4), you can see that the optimiser has certainly found "better" parameter sets from the point of view of the summary statistics (Nash-Sutcliffe scores etc.). However, if you look at the plots, the "by eye" fit from the manual calibration is still clearly better. This is because the optimiser is minimising the sum of squared errors - a metric that strongly penalises large outliers. The "best" result from the optimiser therefore tries to fit the peaks in the observed series, at the expense of poor fits elsewhere. Since metrics like N-S are closely related to the sum of squared errors, this approach gives impressive summary statistics, but actually rather poor simulations. The choice of appropriate summary metrics for assessing water quality time series is still an active area of research.